backend:
  name: github
  repo: abdul-hayee-jamali12/abdul-hayee-jamali12.github.io
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "_data/profile.json"
        label: "Profile Info"
        name: "profile"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Bio", name: "bio", widget: "text"}
          - {label: "LinkedIn URL", name: "linkedin", widget: "string"}

  - name: "cert_data"
    label: "Certificates"
    files:
      - file: "_data/certificates.json"
        label: "Certificates List"
        name: "certificates"
        fields:
          - label: "Certificates"
            name: "items"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Issuer", name: "issuer", widget: "string"}
              - {label: "Date", name: "date", widget: "string"}
