backend:
  name: github
  repo: abdul-hayee-jamali12/abdul-hayee-jamali12.github.io
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "certificates"
  - label: "Certificates"
  - folder: "content/certificates"
  - create: true
  - fields:
      - {label: "Certificate Title", name: "title", widget: "string"}
      - {label: "Issuer", name: "issuer", widget: "string"}
      - {label: "Issue Date", name: "date", widget: "date"}
      - {label: "Certificate File (PDF or Image)", name: "file", widget: "file"}

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    fields:
      - {label: "Project Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "GitHub Link", name: "link", widget: "string", required: false}
